version: '3'

services:
  todo:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: todo
    container_name: todo
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
    ports:
      - "3000:3000"
volumes:
  web-root:

networks:
  app-network:
    driver: bridge